/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
              "surface-variant": "#e1e3e4",
              "primary": "#006067",
              "on-secondary-fixed": "#001e30",
              "tertiary-fixed-dim": "#b8cac9",
              "on-secondary-fixed-variant": "#254a65",
              "on-surface-variant": "#3e494a",
              "primary-fixed": "#96f1fa",
              "surface-container-low": "#f2f4f5",
              "surface-dim": "#d8dadb",
              "on-primary-fixed-variant": "#004f54",
              "primary-fixed-dim": "#7ad5dd",
              "on-tertiary-fixed": "#0e1e1e",
              "error": "#ba1a1a",
              "secondary-container": "#badeff",
              "surface-container-lowest": "#ffffff",
              "surface": "#f8fafb",
              "surface-container": "#eceeef",
              "tertiary-container": "#617271",
              "on-secondary-container": "#3f637e",
              "background": "#f8fafb",
              "surface-container-highest": "#e1e3e4",
              "error-container": "#ffdad6",
              "on-primary-container": "#d0fbff",
              "on-error": "#ffffff",
              "on-error-container": "#93000a",
              "outline-variant": "#bdc9ca",
              "on-background": "#191c1d",
              "secondary": "#3f627e",
              "secondary-fixed": "#cbe6ff",
              "inverse-primary": "#7ad5dd",
              "surface-tint": "#006970",
              "inverse-on-surface": "#eff1f2",
              "inverse-surface": "#2e3132",
              "on-tertiary": "#ffffff",
              "surface-bright": "#f8fafb",
              "primary-container": "#007b83",
              "tertiary": "#495a59",
              "on-surface": "#191c1d",
              "surface-container-high": "#e6e8e9",
              "on-tertiary-container": "#e5f7f6",
              "on-secondary": "#ffffff",
              "on-primary-fixed": "#002022",
              "outline": "#6e797a",
              "on-tertiary-fixed-variant": "#3a4a49",
              "secondary-fixed-dim": "#a7cbeb",
              "on-primary": "#ffffff",
              "tertiary-fixed": "#d4e6e5"
            },
            fontFamily: {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Manrope", "sans-serif"]
            },
        },
    },
    plugins: [],
}
